---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [always]

# Install git from source when git_install_from_source is true.
- include: install-from-source.yml
  when: pound_install_from_source == true
  tags: [pound_build]

- include: install-package.yml
  when: pound_install_from_source == false


- name: Copy the pound.cfg template file
  template:
    src: pound.cfg.j2
    dest: "{{ pound_cfg_file }}"
    backup: yes
  notify:
   - restart pound


- include: configure-logging.yml
  when: pound_custom_log == true and ansible_os_family == "Debian"
  tags: [pound_log]


- name: Configure pound to start in /etc/default/pound
  lineinfile:
    dest: "/etc/default/pound"
    regexp: "^startup="
    line: "startup=1"
  notify:
   - restart pound
  when: ansible_os_family == 'Debian'


